# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-09-17 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210917_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguindo',
            unique_together=set([('de', 'para')]),
        ),
    ]
